<?php
/**
 * @author Barwenock
 * @copyright Copyright (c) Barwenock
 * @package Rich Snippets for Magento 2
 */

/**
 * @var $block \Barwenock\RichSnippets\Block\CategorySnippet
 */
?>
<?php if ($block->getCategorySnippetStatus() === 1): ?>
    <script type="application/ld+json">
        <?= /* @noEscape */ $block->getCategorySnippet(); ?>
    </script>

    <script type="application/ld+json">
        <?= /* @noEscape */ $block->getProductsCategorySnippet(); ?>
    </script>
<?php endif; ?>
